POST http://localhost:3000/user
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "person"
}
###
# @name allUsers
GET http://localhost:3000/user
###
@userId = {{allUsers.response.body.$[0].id}}

GET http://localhost:3000/user/{{userId}}
###